name: build

on:
  push:
    branches: [master]
  #release:
    #types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          # upx 3.96
          sudo apt-get update
          sudo rm -rf /usr/bin/go*
          sudo rm -rf /usr/local/go
          wget https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz -O go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          mv upx-3.96-amd64_linux/upx .
          rm -rf upx-3.96-amd64_linux*
      - name: build
        run: |
          mkdir tmp
          mkdir bin
          # Do not use "--depth=1" due to tags
          git clone https://github.com/v2fly/v2ray-core.git
          cd v2ray-core
          git checkout tags/v4.30.0
          cd ..
          sed -i 's/_ "v2ray.com\/core\/main\/json"/\/\/_ "v2ray.com\/core\/main\/json"/' v2ray-core/main/distro/all/all.go
          sed -i 's/\/\/ _ "v2ray.com\/core\/main\/jsonem"/_ "v2ray.com\/core\/main\/jsonem"/' v2ray-core/main/distro/all/all.go
          wget https://raw.githubusercontent.com/felix-fly/v2ray-openwrt/master/build.sh
          chmod +x ./build.sh
          ./build.sh linux amd64
          ./build.sh linux arm64
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: bin
